# GENERATE 'SECRET_KEY' VIA ANY MEANS YOU PREFER
# DO NOT USE THE DEFAULT SECRET KEY (THIS SERVES AS A TEMPLATE ONLY)

class Config:
    SECRET_KEY = 'o2IlisxsQy7lFEPBUeVjZX75HRy'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///data.db'

